//Take from: https://philosophy-quotes-api.glitch.me/quotes
export default [
	{ source: "René Descartes", philosophy: "Rationalism", quote: "Except our own thoughts, there is nothing absolutely in our power." },
	{ source: "John Locke", philosophy: "Empiricism", quote: "Parents wonder why the streams are bitter, when they themselves poison the fountain." },
	{
		source: "Aristotle",
		philosophy: "Classical Greek",
		quote: "I count him braver who overcomes his desires than him who conquers his enemies, for the hardest victory is over self.",
	},
	{ source: "Alan Watts", philosophy: "Mysticism", quote: "The more a thing tends to be permanent, the more it tends to be lifeless." },
	{ source: "Fyodor Dostoyevsky", philosophy: "Existentialism", quote: "The soul is healed by being with children." },
	{ source: "Rumi", philosophy: "Mysticism", quote: "Don't be satisfied with stories, how things have gone with others. Unfold your own myth." },
	{ source: "Leibniz", philosophy: "Rationalism", quote: "Nihil est sine ratione. [There is nothing without a reason.]" },
	{
		source: "Henry David Thoreau",
		philosophy: "Transcendentalism",
		quote: "Do not be too moral. You may cheat yourself out of much life so. Aim above morality. Be not simply good, be good for something.",
	},
	{ source: "Carl G. Jung", philosophy: "Mysticism", quote: "In all chaos there is a cosmos, in all disorder a secret order." },
	{ source: "Henry David Thoreau", philosophy: "Transcendentalism", quote: "How vain it is to sit down to write when you have not stood up to live." },
	{
		source: "Leibniz",
		philosophy: "Rationalism",
		quote: "Perceptions which are at present insensible may grow some day: nothing is useless, and eternity provides great scope for change.",
	},
	{ source: "John Locke", philosophy: "Empiricism", quote: "No man's knowledge here can go beyond his experience." },
	{ source: "Jean-Paul Sartre", philosophy: "Existentialism", quote: "There may be more beautiful times, but this one is ours." },
	{
		source: "George Berkeley",
		philosophy: "Empiricism",
		quote: "Truly my opinion is, that all our opinions are alike vain and uncertain. what we approve today, we condemn tomorrow. Nature certainly never intended us for speculation.",
	},
	{ source: "Henry David Thoreau", philosophy: "Transcendentalism", quote: "All good things are wild and free." },
	{
		source: "Leibniz",
		philosophy: "Rationalism",
		quote: "It is unworthy of excellent men to lose hours like slaves in the labour of calculation which could safely be relegated to anyone else if machines were used.",
	},
	{ source: "Henry David Thoreau", philosophy: "Transcendentalism", quote: "Disobedience is the true foundation of liberty. The obedient must be slaves." },
	{
		source: "Ralph Waldo Emerson",
		philosophy: "Transcendentalism",
		quote:
			"Is it so bad, then, to be misunderstood? Pythagoras was misunderstood, and Socrates, and Jesus, and Luther, and Copernicus, and Galileo, and Newton, and every pure and wise spirit that ever took flesh. To be great is to be misunderstood.",
	},
	{
		source: "Friedrich Nietzsche",
		philosophy: "Existentialism",
		quote: "Whoever fights monsters should see to it that in the process he does not become a monster. And if you gaze long enough into an abyss, the abyss will gaze back into you.",
	},
	{
		source: "Baruch Spinoza",
		philosophy: "Rationalism",
		quote: "The highest activity a human being can attain is learning for understanding, because to understand is to be free.",
	},
	{
		source: "Jean-Paul Sartre",
		philosophy: "Existentialism",
		quote: "Man is condemned to be free; because once thrown into the world, he is responsible for everything he does. It is up to you to give [life] a meaning.",
	},
	{
		source: "René Descartes",
		philosophy: "Rationalism",
		quote:
			"I suppose therefore that all things I see are illusions; I believe that nothing has ever existed of everything my lying memory tells me. I think I have no senses. I believe that body, shape, extension, motion, location are functions. What is there then that can be taken as true? Perhaps only this one thing, that nothing at all is certain.",
	},
	{
		source: "Baruch Spinoza",
		philosophy: "Rationalism",
		quote: "I have made a ceaseless effort not to ridicule, not to bewail, not to scorn human actions, but to understand them.",
	},
	{
		source: "Aristotle",
		philosophy: "Classical Greek",
		quote: "Those who educate children well are more to be honored than they who produce them; for these only gave them life, those the art of living well.",
	},
	{ source: "David Hume", philosophy: "Empiricism", quote: "A wise man, therefore, proportions his belief to the evidence." },
	{ source: "Ralph Waldo Emerson", philosophy: "Transcendentalism", quote: "When it is dark enough, you can see the stars." },
	{ source: "Plato", philosophy: "Classical Greek", quote: "The price good men pay for indifference to public affairs is to be ruled by evil men." },
	{ source: "Ralph Waldo Emerson", philosophy: "Transcendentalism", quote: "It is one of the blessings of old friends that you can afford to be stupid with them." },
	{ source: "George Berkeley", philosophy: "Empiricism", quote: "HE who says there is no such thing as an honest man, you may be sure is himself a knave." },
	{
		source: "Friedrich Nietzsche",
		philosophy: "Existentialism",
		quote:
			"The individual has always had to struggle to keep from being overwhelmed by the tribe. If you try it, you will be lonely often, and sometimes frightened. But no price is too high to pay for the privilege of owning yourself.",
	},
	{
		source: "Rumi",
		philosophy: "Mysticism",
		quote: "Dance, when you're broken open. Dance, if you've torn the bandage off. Dance in the middle of the fighting. Dance in your blood. Dance when you're perfectly free.",
	},
	{ source: "Fyodor Dostoyevsky", philosophy: "Existentialism", quote: "But how could you live and have no story to tell?" },
	{
		source: "Christopher McCandless",
		philosophy: "Transcendentalism",
		quote: "I read somewhere... how important it is in life not necessarily to be strong... but to feel strong.",
	},
	{ source: "Plato", philosophy: "Classical Greek", quote: "The measure of a man is what he does with power." },
	{
		source: "Baruch Spinoza",
		philosophy: "Rationalism",
		quote:
			"I would warn you that I do not attribute to nature either beauty or deformity, order or confusion. Only in relation to our imagination can things be called beautiful or ugly, well-ordered or confused.",
	},
	{ source: "Aristotle", philosophy: "Classical Greek", quote: "Those who know, do. Those that understand, teach." },
	{
		source: "Ralph Waldo Emerson",
		philosophy: "Transcendentalism",
		quote: "To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment.",
	},
	{ source: "Plato", philosophy: "Classical Greek", quote: "The madness of love is the greatest of heaven's blessings." },
	{
		source: "Henry David Thoreau",
		philosophy: "Transcendentalism",
		quote: "Nothing makes the earth seem so spacious as to have friends at a distance; they make the latitudes and longitudes.",
	},
	{
		source: "George Berkeley",
		philosophy: "Empiricism",
		quote: "I know what I mean by the term I and myself; and I know this immediately, or intuitively, though I do not perceive it as I perceive a triangle, a colour, or a sound.",
	},
	{
		source: "John Locke",
		philosophy: "Empiricism",
		quote: "To love truth for truth's sake is the principal part of human perfection in this world, and the seed-plot of all other virtues.",
	},
	{ source: "Epictetus", philosophy: "Stoicism", quote: "First say to yourself what you would be; and then do what you have to do." },
	{ source: "Christopher McCandless", philosophy: "Transcendentalism", quote: "Happiness is only real, when shared." },
	{ source: "Plato", philosophy: "Classical Greek", quote: "You should not honor men more than truth." },
	{ source: "John Locke", philosophy: "Empiricism", quote: "Few men think, yet all will have opinions. Hence men’s opinions are superficial and confused." },
	{ source: "Jean-Paul Sartre", philosophy: "Existentialism", quote: "Life begins on the other side of despair." },
	{ source: "Jean-Paul Sartre", philosophy: "Existentialism", quote: "If you're lonely when you're alone, you're in bad company." },
	{ source: "Alan Watts", philosophy: "Mysticism", quote: "You are an aperture through which the universe is looking at and exploring itself." },
	{ source: "René Descartes", philosophy: "Rationalism", quote: "Cogito ergo sum. (I think, therefore I am.)" },
	{ source: "John Locke", philosophy: "Empiricism", quote: "I have always thought the actions of men the best interpreters of their thoughts." },
	{
		source: "Henry David Thoreau",
		philosophy: "Transcendentalism",
		quote:
			"I find it wholesome to be alone the greater part of the time. To be in company, even with the best, is soon wearisome and dissipating. I love to be alone. I never found the companion that was so companionable as solitude.",
	},
	{ source: "Marcus Aurelius", philosophy: "Stoicism", quote: "Waste no more time arguing what a good man should be. Be One." },
	{ source: "Rumi", philosophy: "Mysticism", quote: "If you are irritated by every rub, how will your mirror be polished?" },
	{ source: "René Descartes", philosophy: "Rationalism", quote: "Conquer yourself rather than the world." },
	{ source: "Baruch Spinoza", philosophy: "Rationalism", quote: "I do not know how to teach philosophy without becoming a disturber of the peace." },
	{ source: "Alan Watts", philosophy: "Mysticism", quote: "Man suffers only because he takes seriously what the gods made for fun." },
	{ source: "Seneca", philosophy: "Stoicism", quote: "Luck is what happens when preparation meets opportunity." },
	{ source: "Ralph Waldo Emerson", philosophy: "Transcendentalism", quote: "The earth laughs in flowers." },
	{ source: "Friedrich Nietzsche", philosophy: "Existentialism", quote: "And those who were seen dancing were thought to be insane by those who could not hear the music." },
	{
		source: "Christopher McCandless",
		philosophy: "Transcendentalism",
		quote:
			"The very basic core of a man's living spirit is his passion for adventure. The joy of life comes from our encounters with new experiences and hence there is no greater joy than to have an endlessly changing horizon, for each day to have a new and different sun.",
	},
	{ source: "Ralph Waldo Emerson", philosophy: "Transcendentalism", quote: "Once you make a decision, the universe conspires to make it happen." },
	{ source: "Seneca", philosophy: "Stoicism", quote: "Sometimes even to live is an act of courage." },
	{
		source: "René Descartes",
		philosophy: "Rationalism",
		quote: "Common sense is the most widely shared commodity in the world, for every man is convinced that he is well supplied with it.",
	},
	{ source: "Plato", philosophy: "Classical Greek", quote: "I am the wisest man alive, for I know one thing, and that is that I know nothing." },
	{ source: "Jean-Paul Sartre", philosophy: "Existentialism", quote: "Better to die on one's feet than to live on one's knees." },
	{ source: "Marcus Aurelius", philosophy: "Stoicism", quote: "The best revenge is not to be like your enemy." },
	{ source: "Epictetus", philosophy: "Stoicism", quote: "No man is free who is not master of himself." },
	{ source: "Henry David Thoreau", philosophy: "Transcendentalism", quote: "Rather than love, than money, than fame, give me truth." },
	{ source: "David Hume", philosophy: "Empiricism", quote: "Reason is, and ought only to be the slave of the passions." },
	{ source: "Plato", philosophy: "Classical Greek", quote: "Be kind, for everyone you meet is fighting a harder battle." },
	{ source: "Leibniz", philosophy: "Rationalism", quote: "He who does not act does not exist." },
	{
		source: "Baruch Spinoza",
		philosophy: "Rationalism",
		quote: "Give up the notion that you must be sure of what you are doing. Instead, surrender to what is real within you, for that alone is sure....you are above everything distressing.",
	},
	{ source: "René Descartes", philosophy: "Rationalism", quote: "There is nothing more ancient than the truth." },
	{ source: "Plato", philosophy: "Classical Greek", quote: "Education is teaching our children to desire the right things." },
	{ source: "John Locke", philosophy: "Empiricism", quote: "There is frequently more to be learned from the unexpected questions of a child than the discourses of men." },
	{
		source: "Christopher McCandless",
		philosophy: "Transcendentalism",
		quote: "In reality nothing is more damaging to the adventurous spirit within a man than a secure future.",
	},
	{ source: "Ralph Waldo Emerson", philosophy: "Transcendentalism", quote: "What lies behind us and what lies before us are tiny matters compared to what lies within us." },
	{ source: "Baruch Spinoza", philosophy: "Rationalism", quote: "In so far as the mind sees things in their eternal aspect, it participates in eternity." },
	{ source: "Carl G. Jung", philosophy: "Mysticism", quote: "Show me a sane man and I will cure him for you." },
	{
		source: "Leibniz",
		philosophy: "Rationalism",
		quote:
			"...it is the knowledge of necessary and eternal truths that distinguishes us from the mere animals and gives us Reason and the sciences, raising us to the knowledge of ourselves and of God...",
	},
	{ source: "David Hume", philosophy: "Empiricism", quote: "Generally speaking, the errors in religion are dangerous; those in philosophy only ridiculous." },
	{ source: "Epictetus", philosophy: "Stoicism", quote: "Don't explain your philosophy. Embody it." },
	{
		source: "Christopher McCandless",
		philosophy: "Transcendentalism",
		quote:
			"The climactic battle to kill the false being within and victoriously conclude the spiritual pilgrimage. No longer to be poisoned by civilization he flees, and walks alone upon the land to become lost in the wild.",
	},
	{
		source: "David Hume",
		philosophy: "Empiricism",
		quote: "Beauty is no quality in things themselves: It exists merely in the mind which contemplates them; and each mind perceives a different beauty.",
	},
	{ source: "Aristotle", philosophy: "Classical Greek", quote: "It is the mark of an educated mind to be able to entertain a thought without accepting it." },
	{ source: "David Hume", philosophy: "Empiricism", quote: "But the life of a man is of no greater importance to the universe than that of an oyster." },
	{ source: "Aristotle", philosophy: "Classical Greek", quote: "The educated differ from the uneducated as much as the living differ from the dead." },
	{ source: "Fyodor Dostoyevsky", philosophy: "Existentialism", quote: "I say let the world go to hell, but I should always have my tea." },
	{
		source: "Plato",
		philosophy: "Classical Greek",
		quote: "We can easily forgive a child who is afraid of the dark; the real tragedy of life is when men are afraid of the light.",
	},
	{ source: "George Berkeley", philosophy: "Empiricism", quote: "If a tree falls in a forest and no one is around to hear it, does it make a sound?" },
	{ source: "Carl G. Jung", philosophy: "Mysticism", quote: "One does not become enlightened by imagining figures of light, but by making the darkness conscious." },
	{ source: "Marcus Aurelius", philosophy: "Stoicism", quote: "The soul becomes dyed with the colour of its thoughts." },
	{ source: "René Descartes", philosophy: "Rationalism", quote: "The reading of all good books is like conversation with the finest men of past centuries." },
	{ source: "Fyodor Dostoyevsky", philosophy: "Existentialism", quote: "The darker the night, the brighter the stars. The deeper the grief, the closer is God!" },
	{ source: "Aristotle", philosophy: "Classical Greek", quote: "Educating the mind without educating the heart is no education at all." },
	{ source: "Seneca", philosophy: "Stoicism", quote: "A wise man is content with his lot, whatever it may be, without wishing for what he has not." },
	{ source: "George Berkeley", philosophy: "Empiricism", quote: "Truth is the cry of all, but the game of few." },
	{
		source: "David Hume",
		philosophy: "Empiricism",
		quote: "It is an absurdity to believe that the Deity has human passions, and one of the lowest of human passions, a restless appetite for applause.",
	},
	{ source: "John Locke", philosophy: "Empiricism", quote: "The only defense against the world is a thorough knowledge of it." },
	{ source: "Epictetus", philosophy: "Stoicism", quote: "First learn the meaning of what you say, and then speak." },
	{ source: "Carl G. Jung", philosophy: "Mysticism", quote: "Until you make the unconscious conscious, it will direct your life and you will call it fate." },
	{ source: "Marcus Aurelius", philosophy: "Stoicism", quote: "If it is not right, do not do it, if it is not true, do not say it." },
	{
		source: "Marcus Aurelius",
		philosophy: "Stoicism",
		quote: "Never let the future disturb you. You will meet it, if you have to, with the same weapons of reason which today arm you against the present.",
	},
	{ source: "Rumi", philosophy: "Mysticism", quote: "The wound is the place where the Light enters you." },
	{
		source: "René Descartes",
		philosophy: "Rationalism",
		quote: "If you would be a real seeker after truth, it is necessary that at least once in your life you doubt, as far as possible, all things.",
	},
	{ source: "Aristotle", philosophy: "Classical Greek", quote: "No great mind has ever existed without a touch of madness." },
	{ source: "Alan Watts", philosophy: "Mysticism", quote: "Muddy water is best cleared by leaving it alone." },
	{ source: "Friedrich Nietzsche", philosophy: "Existentialism", quote: "He who has a why to live for can bear almost any how." },
	{ source: "George Berkeley", philosophy: "Empiricism", quote: "To be is to be perceived." },
	{ source: "Aristotle", philosophy: "Classical Greek", quote: "A friend to all is a friend to none." },
	{
		source: "Fyodor Dostoyevsky",
		philosophy: "Existentialism",
		quote: "The mystery of human existence lies not in just staying alive, but in finding something to live for.",
	},
	{
		source: "Leibniz",
		philosophy: "Rationalism",
		quote: "There is nothing in the understanding which has not come from the senses, except the understanding itself, or the one who understands.",
	},
	{ source: "Leibniz", philosophy: "Rationalism", quote: "This is the best of all possible worlds." },
	{ source: "Henry David Thoreau", philosophy: "Transcendentalism", quote: "Books are the treasured wealth of the world and the fit inheritance of generations and nations" },
	{ source: "Epictetus", philosophy: "Stoicism", quote: "It's not what happens to you, but how you react to it that matters." },
	{ source: "Plato", philosophy: "Classical Greek", quote: "Only the dead have seen the end of war." },
	{ source: "Seneca", philosophy: "Stoicism", quote: "Difficulties strengthen the mind, as labor does the body." },
	{
		source: "Carl G. Jung",
		philosophy: "Mysticism",
		quote: "Your visions will become clear only when you can look into your own heart. Who looks outside, dreams; who looks inside, awakes.",
	},
	{ source: "George Berkeley", philosophy: "Empiricism", quote: "The only things we perceive are our perceptions." },
	{ source: "Rumi", philosophy: "Mysticism", quote: "Yesterday I was clever, so I wanted to change the world. Today I am wise, so I am changing myself." },
	{ source: "Seneca", philosophy: "Stoicism", quote: "It is the power of the mind to be unconquerable." },
	{ source: "Plato", philosophy: "Classical Greek", quote: "When men speak ill of thee, live so as nobody may believe them." },
	{
		source: "Ralph Waldo Emerson",
		philosophy: "Transcendentalism",
		quote: "I cannot remember the books I've read any more than the meals I have eaten; even so, they have made me.",
	},
	{ source: "Alan Watts", philosophy: "Mysticism", quote: "Trying to define yourself is like trying to bite your own teeth." },
	{
		source: "David Hume",
		philosophy: "Empiricism",
		quote: "...no testimony is sufficient to establish a miracle, unless the testimony be of such a kind, that its falsehood would be more miraculous, than the fact, which it endeavors to establish.",
	},
	{ source: "Baruch Spinoza", philosophy: "Rationalism", quote: "If you want the present to be different from the past, study the past." },
	{
		source: "John Locke",
		philosophy: "Empiricism",
		quote: "New opinions are always suspected, and usually opposed, without any other reason but because they are not common.",
	},
	{ source: "Friedrich Nietzsche", philosophy: "Existentialism", quote: "That which does not kill us makes us stronger." },
];